### ISSUE TITLE
Implement support for Wayland DE

### ISSUE THREAD

**Issue by dynobo** [BoboTiG/python-mss#155]
General information:

* OS name: __Ubuntu__
* OS version: _20.04_
* OS architecture: _64 bits_
* Resolutions:
    * Monitor 1: _1920x1080_
* Python version: _3.8.2_
* MSS version: __5.0.0__

For GNU/Linux users:

* Display server protocol and version, if known: __Wayland__
* Desktop Environment: _Gnome_
* Composite Window Manager name and version: __Unknown__

### Description of the warning/error

When running `mss` under Wayland, it crashs. As far as I understand from the source code, `mss` currently uses xlib for Linux, which seems to (unsurprisingly) not work on Wayland. It would be very cool to have wayland support implemented, as it becomes more and more popular.

### Full message

_Example:_ Executing the following snippet under X works perfectly, while under Wayland it produces an error.
Example: 

**Snippet:**
```python
import mss
fn = mss.mss().shot(mon=-1, output="screenshot.png")
print(fn)
```

**Error on Wayland:**
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/holger/.local/lib/python3.8/site-packages/mss/factory.py", line 41, in mss
    return linux.MSS(**kwargs)
  File "/home/holger/.local/lib/python3.8/site-packages/mss/linux.py", line 226, in __init__
    self.root = self.xlib.XDefaultRootWindow(MSS.display)
  File "/home/holger/.local/lib/python3.8/site-packages/mss/linux.py", line 175, in validate
    raise ScreenShotError(err, details=details)
mss.exception.ScreenShotError: XDefaultRootWindow() failed
```

### Other details

A lot of screenshot tools (e.g. shutter) have this issue, because screenshots seem to work completely differently in Wayland (to improve security). Applications that *do* work are e.g.:

- [gnome-screenshot](https://gitlab.gnome.org/GNOME/gnome-screenshot/tree/master/), which is e.g. leveraged by the python-lib [pyscreenshot](https://pypi.org/project/pyscreenshot/)
- [flameshot](https://github.com/lupoDharkael/flameshot) works too, but seems not to have implemented the "proper" way here (see below). 

**A proper way to do screenshots under Wayland is referenced in [a flameshot issue](https://github.com/lupoDharkael/flameshot/issues/446#issue-397993840) and might help solving this in `mss`, too. The main statement from that issue:**

> The cross-platform way to take screenshots on Wayland is via [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal) (which also works outside of Flatpak). See https://github.com/flatpak/xdg-desktop-portal/blob/master/data/org.freedesktop.portal.Screenshot.xml

**Comment by BoboTiG** [comment]
Hello,

Thanks for starting the discussion :)
It would be cool to have MSS working on Wayland, I will check that when I can (PRs are still very welcome too :smiley:).

**Comment by BoboTiG** [comment]
Some information: https://fedoraproject.org/wiki/How_to_debug_Wayland_problems#Screen_capture_is_not_available_with_usual_apps

**Comment by DjinNO** [comment]
really looking fow wayland support

**Comment by surajRathi** [comment]
Hello,

I started looking at wayland support. I have worked on a very basic (incomplete) implementation [repository](https://github.com/surajRathi/python-mss/tree/surajRathi_wayland-support) . 

However I am getting horrible FPS (~3.5) and it pulls in two external dependencies (python-dbus and pygoobject).

There are two points of interest:
1. I think xdg-desktop-portal seems to only give the current monitor. I do not have an external monitor. I may try with virtual outputs in the future.
2. Flow:
2.1. Call method `Screenshot` on Service `org.freedesktop.portal.Desktop`,  with object `/org/freedesktop/portal/desktop`, and interface `org.freedesktop.portal.Screenshot`.
This will return the path of an object: `request_path`
2.2 Subscribe to a signal on Service `org.freedesktop.portal.Desktop` on the object `request_path` and interface `org.freedesktop.portal.Request`.
2.3 Run the Main Loop (!!!). After a while we will receive a _file_ path.
2.4 Open the file and create a screenshot object.

This project (from what I understand) is supposed to be fast and no dependencies. 
Further steps to be taken:
- Monitor Support
- Use libdbus directly and use a custom event loop. (*absolutely no idea where to start from*) 

Concerns: 
1. The dbus event loop seems to be taking ~75% of the time (the remaining 30% being mainly reading the file from disk to a screenshot object). With this latency is xdg-desktop-portal suitable for the python-mss project?

2. Should I add/modify the `Screenshot` object constructors to load images from a file more efficiently?


I have not been able to run the tests as the `pygoobject` dependency is causing issues. I am not that familiar with `tox`.

I have not made a pull request as this is very very preliminary.

Apologies if I have skipped a step or not seen another discussion.

**Comment by adeliktas** [comment]
A bump should be no issue as long as this issue is open and there is demand for wayland (or Xwayland on Gnome 40.0 in my case). I've tried the commits of surajRathi, but unfortunately receive NotImplementedError for _monitors_impl. Mss is a dependency for python-imagesearch, which i originally intended to use.

**Comment by gitagogaming** [comment]
I recently ran into a similar issue trying to use mss.grab on Fedora 36.   The default is wayland and after a bit of research I learned that it still does not work on wayland.  
So onto a little extra bump here to anyone that understands the issue at hand perhaps

**Comment by cactorium** [comment]
Just wanted to add a little bit in case anyone wants to try to implement it; it looks like most desktop environments have opted to support xdg-desktop-portal, which exposes a Screencasting API, which provides a Pipewire interface to the screencast: https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-org.freedesktop.portal.ScreenCast It looks like there's some talk in python-pillow to use this in case that provides some more useful resources: https://github.com/python-pillow/Pillow/issues/6392

**Comment by calllivecn** [comment]
It's 2025, is there any progress?

**Comment by AuroraWright** [comment]
Not sure if it can be of help but I have a shim which partially emulates mss with the Wayland screencast api:
https://github.com/AuroraWright/owocr/blob/master/owocr/wayland_mss_shim.py
Sadly it needs to approve/select what to share with a portal popup and it has some more limitations (I show a single fake monitor in mss.monitors with the dimensions of the area/window the user has selected, I don't think there's a way to re-use the current mss design as-is on Wayland right now, it won't work in a multi-process context, you need to manually specify a framerate, etc)

**Comment by ChaoticByte** [comment]
> It's 2025, is there any progress?

It's 2026 now and X11 support is slowly being dropped in some Desktop Environments, but hassle-free solutions for (fast) screen grabbing seem rare :(

**Comment by andypiper** [comment]
I've been able to do something similar to https://github.com/AuroraWright/owocr/blob/master/owocr/wayland_mss_shim.py for something I worked on - in that case the approval popup from the portal is an acceptable "price" to pay for what I wanted, but I'm also not fully replicating what the mss library offers.

**Comment by eduarcor** [comment]
I really love this library, and it works amazingly well.
I’m also very glad to see new versions continuing to improve performance.

Sadly, the dominance of X11 on Linux is gradually coming to an end, and many professional and workstation environments are moving toward Wayland. Unless MSS evolves in that direction as well, it may become harder to use in those environments. I’m surprised there has not yet been more visible movement toward Wayland support.

Thank you again for all your work, and I hope Wayland support can become a priority.

**Comment by hatfield-c** [comment]
@andypiper can you do a PR to bring your updates into mss? I'd really like to have a unified library across all my OS instances

**Comment by hatfield-c** [comment]
this comment suggests a screengrab library available for wayland in python. I haven't tested it though:
- https://github.com/openrecall/openrecall/issues/10#issuecomment-2156366402

the arch wiki suggests a number of utilities to do screenshots on wayland:
- https://wiki.archlinux.org/title/Screen_capture#Wayland

**Comment by theweirdbyte** [comment]
That's the current scheme right now:

### Latency & Performance Comparison: Screen Capture Methods on Linux

The following benchmarks compare capture latency for Python-based screen recording across X11 and Wayland environments. Lower latency is critical for real-time applications (e.g., computer vision, streaming).

| Method | Environment | Avg. Latency (1080p) | Mechanism | Notes |
| :--- | :--- | :--- | :--- | :--- |
| **`mss` (Native)** | **X11** | **~5–15 ms** | Direct `XGetImage` / SHM | **Fastest overall.** Direct memory access; no compositor overhead. |
| **`grim` + `subprocess`** | **Wayland** (wlroots: Sway/Hyprland) | **~10–25 ms** | `wlr-screencopy` protocol | **Fastest on Wayland.** Direct compositor buffer copy.  Near-native X11 speeds. |
| **PipeWire** | **Wayland** (Universal: GNOME/KDE) | **~30–60+ ms** | DBus Portal + Stream | **Universal but slower.** Overhead from stream negotiation and buffer copying.  |
| **Xwayland + `mss`** | **Wayland** (via X11 compatibility) | **~40–80 ms** | X11 translation layer | **High overhead.** Adds ~3ms+ input lag plus capture translation costs.  Avoid for low-latency needs. |
| **`pyautogui` / `pyscreenshot`** | **Wayland** | **Variable / Broken** | Fallback methods | **Unreliable.** Often fails or resorts to slow DBus methods. |

#### Key Findings
1.  **X11 Baseline**: Native `mss` on X11 remains the performance king (~10ms) due to unrestricted memory access.
2.  **Wayland Native**: On `wlroots` compositors (Sway, Hyprland), `grim` is the optimal choice, matching X11 performance (~15ms) by bypassing portal overhead. 
3.  **Wayland Universal**: On GNOME/KDE, PipeWire is the *only* viable native option but introduces significant latency (~50ms) due to its streaming architecture. 
4.  **Xwayland Penalty**: Running X11 tools (`mss`) inside Wayland via Xwayland is the **slowest** method, combining translation overhead with legacy protocol inefficiencies.

**Comment by eduarcor** [comment]
That's the current scheme right now:

### Latency & Performance Comparison: Screen Capture Methods on Linux

| Method | Environment | Avg. Latency (1080p) | Mechanism | Notes |
| :--- | :--- | :--- | :--- | :--- |
| **`mss` (Native)** | **X11** | **~5–15 ms** | Direct `XGetImage` / SHM | **Fastest overall.** Direct memory access; no compositor overhead. |
| **`grim` + `subprocess`** | **Wayland** (wlroots: Sway/Hyprland) | **~10–25 ms** | `wlr-screencopy` protocol | **Fastest on Wayland.** Direct compositor buffer copy.  Near-native X11 speeds. |
| **PipeWire** | **Wayland** (Universal: GNOME/KDE) | **~30–60+ ms** | DBus Portal + Stream | **Universal but slower.** Overhead from stream negotiation and buffer copying.  |
| **Xwayland + `mss`** | **Wayland** (via X11 compatibility) | **~40–80 ms** | X11 translation layer | **High overhead.** Adds ~3ms+ input lag plus capture translation costs.  Avoid for low-latency needs. |
| **`pyautogui` / `pyscreenshot`** | **Wayland** | **Variable / Broken** | Fallback methods | **Unreliable.** Often fails or resorts to slow DBus methods. |
