### ISSUE TITLE
Value error on macbook

### ISSUE THREAD

**Issue by Kanter666** [BoboTiG/python-mss#23]
Hello,
I was trying to use your library on my macbook and I keep getting this error messages.

General informations:

* OS name: macOS Sierra
* OS version: 10.12.6 (16G29)
* OS architecture: 64 bits
* Result of the command `python --version`: Python 3.6.2

### Description of the warning/error

When I use master branch I am able to do a few screenshots, that are getting smaller, and then I get the first error. It works the same way every time I restart python - first screenshot is good, another 3 are getting smaller and then I get an error. 
When I switched to dev branch and I get immediately Value error.

### Full message

* Master branch
```
>>> from mss import mss
>>> with mss() as sct:
...     for x in range(10):
...             sct.shot()
... 
'monitor-1.png'
'monitor-1.png'
'monitor-1.png'
'monitor-1.png'
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/local/lib/python3.6/site-packages/mss/base.py", line 131, in shot
    return next(self.save(**kwargs))
  File "/usr/local/lib/python3.6/site-packages/mss/base.py", line 121, in save
    to_png(sct.rgb, sct.size, output)
  File "/usr/local/lib/python3.6/site-packages/mss/base.py", line 255, in rgb
    self.raw[2::4], self.raw[1::4], self.raw[0::4]
ValueError: attempt to assign bytes of size 253362176 to extended slice of size 1327104000
```

* Dev branch
```
>>> from mss import mss
>>> with mss() as sct:
...     sct.shot()
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/git/python-mss/mss/base.py", line 124, in shot
    return next(self.save(**kwargs))
  File "/git/python-mss/mss/base.py", line 114, in save
    to_png(sct.rgb, sct.size, output)
  File "/git/python-mss/mss/screenshot.py", line 133, in rgb
    self.raw[2::4], self.raw[1::4], self.raw[0::4]
ValueError: attempt to assign bytes of size 5184000 to extended slice of size 1296000
```

### Other details

I tried also `for filename in sct.save():
print(filename)` but it crashed with same error messages.

**Comment by BoboTiG** [comment]
Hello,

Thanks for the report. I just tried with the fresh `dev` branch (latest commit is from several minutes ago) and I get good results:

``` python
>>> from mss import mss
>>> with mss() as sct:
...     for x in range(10):
...         sct.shot()
...
'monitor-1.png'
'monitor-1.png'
'monitor-1.png'
'monitor-1.png'
'monitor-1.png'
'monitor-1.png'
'monitor-1.png'
'monitor-1.png'
'monitor-1.png'
'monitor-1.png'
```

Frop my side, it works fine with Python 2.7.13 and 3.6.2. Could you try with the latest dev branch and give me feedbacks please?

**Comment by Kanter666** [comment]
I am still getting the ValueError even with the latest dev branch.

**Comment by BoboTiG** [comment]
What is the content of `sct.monitors`?

**Comment by karanlyons** [comment]
I’m seeing this issue, too:

```python3
>>> from mss.darwin import MSS as mss
>>> mss().monitors
[{'left': 0, 'top': 0, 'width': 1440, 'height': 900}, {'left': 0, 'top': 0, 'width': 1440, 'height': 900}]
>>> mss().shot()
ValueError: attempt to assign bytes of size 5184000 to extended slice of size 1296000
```

1296000 pixels would represent a single 1440x900 display. The true display size is 2880x1800, however, for 5184000 pixels.

It appears that the correct way to get the resolution of the display is to pass it into `CGDisplayCopyDisplayMode` and then use `CGDisplayModeGetHeight`/`CGDisplayModeGetWidth`.

**Comment by BoboTiG** [comment]
Wow, great analyse!
Do you think you can try a patch and send a PR?

**Comment by karanlyons** [comment]
I can post a *partial* patch, but I don’t understand `_crop_width` in regards to whether the black pixel padding is based on the rect width in *screen* coordinates not being a multiple of 16 or if it’s the rect in *pixel* coordinates. The documentation on `CGWindowListCreateImage` doesn’t mention this padding at all.

I think in this case what you want to *actually* do is take the final CGImage and strip the padding (if any) by using `CGImageGetBytesPerRow` and `CGImageGetBitsPerPixel` to get the actual number of bytes in each row of the image and strip off the padding.

I’ve opened a PR that makes all these changes, though you may have some quibbles as to style.
