### ISSUE TITLE
AttributeError: '_thread._local' object has no attribute 'srcdc'

### ISSUE THREAD

**Issue by Hecto-r** [BoboTiG/python-mss#273]
MSS Version: 9.0.1
Python Version: 3.10.11
Windows 10 22H2

Exception in thread Thread-1 (update):
Traceback (most recent call last):
  File "C:threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "d:PlayerHealth.py", line 29, in update
    img = np.array(self.ms.grab(self.healthBox))
  File "C:mss\base.py", line 90, in grab
    screenshot = self._grab_impl(monitor)
  File "C:mss\windows.py", line 235, in _grab_impl
    srcdc, memdc = self._handles.srcdc, self._handles.memdc
AttributeError: '_thread._local' object has no attribute 'srcdc'

```
class PlayerHealth:

    def init(self):
        # Initialize variables
        self.ms = mss.mss()
        self.healthBox = {'top': 45, 'left': 100, 'width': 100, 'height': 20}
        self.healthPercentage = 100

    def start(self):
        # Start the thread that reads frames from the video stream
        Thread(target=self.update,args=()).start()
        return self

    def update(self):
        # Keep looping indefinitely until the thread is stopped
        while True:
            time.sleep(1)
            # Otherwise, grab the next frame from the stream
            img = Image.frombytes('RGB', (100, 20), self.ms.grab(self.healthBox).rgb)
            screen = cv2.cvtColor(np.array(img), cv2.COLOR_BGR2GRAY)

            # Save so we can see what we grabbed - Debug purpose only
            cv2.imwrite("health.png",screen)
```
            
```
class main:
    def testObject():
      aPlayerHealth = PlayerHealth().start()
      while True:
          time.sleep(5)
          print(aPlayerHealth.read())
```

**Comment by Hecto-r** [comment]
well fixed the issue by changing the following if anyone else runs into this:

```
def update(self):
        # Keep looping indefinitely until the thread is stopped
        while True:
            time.sleep(1)
            with mss.mss() as sct:
                # Otherwise, grab the next frame from the stream
                img = Image.frombytes('RGB', (100, 20), sct.grab(self.healthBox).rgb)
                screen = cv2.cvtColor(np.array(img), cv2.COLOR_BGR2GRAY)
```

**Comment by lrq3000** [comment]
I have the same error happening now, it never happened before. I have no idea of the cause, but it's totally breaking my app.

Your solution is disadvised in the documentation, `with mss.mss() as sct:` should be out of the loop to avoid instanciating non stop the same object.

**Comment by Hecto-r** [comment]
> Your solution is disadvised in the documentation, `with mss.mss() as sct:` should be out of the loop to avoid instanciating non stop the same object.
> 

Yeah I’ll leave the issue open to try and get a real fix. The other solution I’ve seen is downgrading to a version that works (possibly v6. I didn’t give that a try though)

**Comment by Sardor3** [comment]
> well fixed the issue by changing the following if anyone else runs into this:
> 
> ```
> def update(self):
>         # Keep looping indefinitely until the thread is stopped
>         while True:
>             time.sleep(1)
>             with mss.mss() as sct:
>                 # Otherwise, grab the next frame from the stream
>                 img = Image.frombytes('RGB', (100, 20), sct.grab(self.healthBox).rgb)
>                 screen = cv2.cvtColor(np.array(img), cv2.COLOR_BGR2GRAY)
> ```

Thanks for temporary solution. It does make sense. I would like to ask any updates on fixing this bug.

**Comment by HSLix** [comment]
The same error occur in my program too. And thankfully, it solved with the method. Hope for any updates on fully fixing the bug.

**Comment by zaixia108** [comment]
same error for me

**Comment by BoboTiG** [comment]
We improved both Linux and Windows code, these situations should either be improved, or fixed.

**Comment by MohammedAlkindi** [comment]
Verified this end to end on native Windows 11 (Python 3.13), since the last state of the thread was "should be fixed" without a run to confirm it.

Reproduction: `mss()` created in the main thread, `.grab()` called from worker threads — one worker, then four concurrently — which is the report's exact shape (`self.ms = mss.mss()` in init, grab from `Thread-1`).

| version | result |
|---|---|
| 9.0.1 (reporter's) | `AttributeError: '_thread._local' object has no attribute 'srcdc'` — 5/5 grabs |
| 10.0.0 | same error, 5/5 |
| 10.1.0 | same error, 5/5 |
| **10.2.0** | **clean — 5/5 grabs succeed, both single-worker and 4 concurrent** |
| current `main` (`5bfbe60`, 11.0.0.dev0) | clean, same runs |

So the failure mode is gone as of **10.2.0**: the thread-local `srcdc`/`memdc` storage that raised here no longer exists — `src/mss/windows/gdi.py` now acquires and releases the device contexts inside each call (the comment at line 346 documents exactly this), so there is no per-thread state left to be uninitialised in a worker thread.

From the Windows side this looks closeable, with "upgrade to ≥ 10.2.0" as the answer for anyone landing here from the traceback. Not covered by my runs: creating `mss()` inside each worker (the old workaround) still works, but I didn't test the Linux/macOS analogues mentioned mid-thread.
