### ISSUE TITLE
AttributeError: _data / "gdi32.GetDIBits() failed" (Windows)

### ISSUE THREAD

**Issue by HatScripts** [BoboTiG/python-mss#59]
General information:

* OS name: _Windows_
* OS version: __10, version 1803__
* OS architecture: _64-bit_
* Resolutions:
    * Monitor 1: _1920x1080_
    * Monitor 2: _1920x1080_
* Python version: _3.6.5_
* MSS version: __3.2.1__

### Description of the warning/error

MSS consistently throws the following error, always after my program has been running for a little over 3 hours, and after successfully capturing many (22,000+) screenshots in that time.

### Full message

```
== 2018-07-15 07:17:17.953381 runtime: 3:09:39.428722 ==
('gdi32.GetDIBits() failed.', {'bits': 0, 'height': 665, 'width': 1033, 'gdi': <WinDLL 'gdi32', handle 7ffeff9b0000 at 0x1e9c1896898>, 'monitor': {'left': -1034, 'top': 31, 'width': 1033, 'height': 665}, 'self': <mss.windows.MSS object at 0x000001E9C1896860>})
Traceback (most recent call last):
  File "D:\IdeaProjects\Python\CaptureTest\main.py", line 98, in <module>
    run()
  File "D:\IdeaProjects\Python\CaptureTest\main.py", line 82, in run
    self.screenshot()
  File "D:\IdeaProjects\Python\CaptureTest\main.py", line 77, in screenshot
    self.im = self.window.screenshot()
  File "D:\IdeaProjects\Python\CaptureTest\main.py", line 84, in screenshot
    im = self.mss_instance.grab(area)
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python36\lib\site-packages\mss\windows.py", line 202, in grab
    del self._data
AttributeError: _data
```

### Other details

I've tried to replicate this error by simply calling `mss.grab(...)` in a while loop and seeing if it breaks after x number of screenshots, but that runs fine for at least 160,000 iterations, so I can't figure out why my program consistently seems to break at ~3 hours runtime.

Upon viewing the MSS source, I realised that the `del self._data` line is directly followed by `raise ScreenShotError('gdi32.GetDIBits() failed.', locals())`, so I suppose my question is:
### What could cause `gdi32.GetDIBits()` to spontaneously fail?

**Comment by BoboTiG** [comment]
Hello,

Thanks for the detailled report. Could you post a minimal code that breaks after 3 hours? I suspect a simple test script as you wrote will not be enough. If you can share the whole project, it could be great.

BTW there is indeed a better error handling to do here.

**Comment by HatScripts** [comment]
I was able to boil my project down into just 50 lines of code, whilst maintaining the bug. Also it now breaks after just ~3 minutes as opposed to ~3 hours because I removed all `sleep`s.

Just make sure you have Notepad open before running it.

For me it consistently raises `ScreenShotError('gdi32.GetDIBits() failed.')` after 9996 screenshots taken.

```py
import win32gui
from datetime import datetime as dt

import mss
import numpy as np
from cv2 import cv2

class Window:
    hwnd = None
    mss_instance = None

    def __init__(self, title):
        self.hwnd = win32gui.FindWindow(None, title)

    def exists(self):
        try:
            win32gui.GetWindowDC(self.hwnd)
            return True
        except:
            return False

    def get_size(self):
        x1, y1, x2, y2 = win32gui.GetWindowRect(self.hwnd)
        x, y, w, h = x1, y1, x2 - x1, y2 - y1
        return x, y, w, h

    def screenshot(self):
        x, y, w, h = self.get_size()
        area = {"left": x, "top": y, "width": w, "height": h}
        if self.mss_instance is None:
            self.mss_instance = mss.mss()
        im = self.mss_instance.grab(area)
        frame = np.array(im, dtype=np.uint8)
        return cv2.cvtColor(frame, cv2.COLOR_BGRA2BGR)

def run():
    start_time = dt.now()
    window = Window("Untitled - Notepad")
    screenshots_taken = 0

    while window.exists():
        now = dt.now()
        print(f"{now - start_time}: {screenshots_taken} screenshots taken")

        im = window.screenshot()
        screenshots_taken += 1

if __name__ == "__main__":
    run()

**Comment by BoboTiG** [comment]
I think I found the cause.

Redefine `Window.exists()` to free the allocated DC:
```python
def exists(self):
    try:
        dc = win32gui.GetWindowDC(self.hwnd)
    except:
        return False
    else:
        win32gui.DeleteObject(dc)
        return True
```
Another benefit: this wil be much faster.

**Comment by BoboTiG** [comment]
If that fixes the issue, do no close it. If we can get better exception details in case of bad `gdi32.GetDIBits()`, it could be a great thing. Do you want to investigate and open an eventual PR?

**Comment by HatScripts** [comment]
Thanks very much, that fixes it.

I clearly wrote that `exists` function without doing enough research into the Win32 API. I was put off from using `IsWindow` by [this SO answer](https://stackoverflow.com/a/2344248/2203482), and so I wrote that hacky solution instead. But I'm pretty sure it still suffers from the same caveats as `IsWindow`, so I might as well simplify the function to:
```py
def exists(self):
    return win32gui.IsWindow(self.hwnd)
```

As for getting better exception details, what exactly would that involve? I don't have much understanding of `win32` or `gdi32`...

**Comment by BoboTiG** [comment]
I was thinking of a way to get a Windows specific error. Or a clue why `gdi32.GetDIBits()` failed. I already tried to call `ctypes.GetLastError()` but it does return no error.

It may be an advanced investigation, perhaps I can do it later if you do not feel confident ;)

**Comment by HatScripts** [comment]
I've tried to look up ways to get a more specific error, but I'm really not familiar with `ctypes` at all. Could something like [this](https://stackoverflow.com/a/29866855/2203482) work, or is that just for WinDLL?

Also, in case I wasn't clear, the `AttributeError` is raised when `mss.grab` is called and it raises `ScreenShotError('gdi32.GetDIBits() failed.')`, but you caught the `ScreenShotError` and then called `mss.grab` again. Example:
```py
while True:
    try:
        mss.grab(area)
    except mss.exception.ScreenShotError:
        print("If this happens...")
    except AttributeError:
        print("...then this happens on the following while loop iteration")
```

This could of course be avoided by simply checking `if self._data:` before calling [`del self._data`](https://github.com/BoboTiG/python-mss/blob/master/mss/windows.py#L202).

**Comment by BoboTiG** [comment]
Yes, the original error can be fixed easily and will be :)

For the other part, do you hink you can give a try to check if it changes something in a better way? You can try to change [this line](https://github.com/BoboTiG/python-mss/blob/master/mss/windows.py#L186) to use `WinDLL` as described in SO and check if you can get an speaking error.

**Comment by BoboTiG** [comment]
OK, long time since this issue was resolved, but i had time to check for a useful error message.
This is was I found: GDI functions do not use `LastError()`, only return `0` on error.

I followed how ReactOS is doing and this is the revelant parts:
- [GetDIBits()](https://github.com/reactos/reactos/blob/c2c66aff7dacc62d125f2cd61d1167e9a2aa3fd6/win32ss/gdi/gdi32/objects/bitmap.c#L354) calls `NtGdiGetDIBitsInternal`;
- [NtGdiGetDIBitsInternal()](https://github.com/reactos/reactos/blob/c2c66aff7dacc62d125f2cd61d1167e9a2aa3fd6/win32ss/gdi/ntgdi/dibobj.c#L1053) calls `GreGetDIBitsInternal`;
- and this is [GreGetDIBitsInternal()](https://github.com/reactos/reactos/blob/c2c66aff7dacc62d125f2cd61d1167e9a2aa3fd6/win32ss/gdi/ntgdi/dibobj.c#L671).

So, there is no way to get some error message ...

Doing this investgation could open a new idea to improve speed on Windows: directly calls `GreGetDIBitsInternal`, if available.

**Comment by botsforprovince** [comment]
To avoid the "mss.exception.ScreenShotError: gdi32.GetDIBits() failed." error that occurs when using mss().grab() multiple times, I used the `with` context manager to ensure that resources are automatically released after the code block is executed.
Now I can use this function smoothly 24/7 without any issues. Feel free to use it!

**Comment by JOOOOO1204** [comment]
thanks man , i  will try it
