### ISSUE TITLE
mss.exception.ScreenShotError: gdi32.GetDIBits() failed.

### ISSUE THREAD

**Issue by NightShadeII** [BoboTiG/python-mss#83]
General information:

* OS name: Windows
* OS version: 10
* OS architecture: 64 bits
* Resolutions:
    * Monitor 1: 1366 x 768
* Python version: 3.6.1
* MSS version: 3.3.2

### Description of the warning/error

Hello, I have been trying to train a model using keras and getting input using mss by taking screenshots. Eventually, always roughly at the same time after 18 episodes or 2880 screenshots I always get this error around this time.

### Full message

```python
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Home\Programming\Python\My Programs\Games\2048 AI\2048 DQN.py", line 259, in <module>
    agent.run()
  File "C:\Users\user\Desktop\Home\Programming\Python\My Programs\Games\2048 AI\2048 DQN.py", line 197, in run
    next_state, reward, done = self.env.step(state, action)
  File "C:\Users\user\Desktop\Home\Programming\Python\My Programs\Games\2048 AI\2048 DQN.py", line 111, in step
    sct = self.window.screenshot()
  File "C:\Users\user\Desktop\Home\Programming\Python\My Programs\Games\2048 AI\2048 DQN.py", line 35, in screenshot
    return np.asarray(mss().grab(self.monitor))[:,:,:3]
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\mss\windows.py", line 223, in grab
    raise ScreenShotError("gdi32.GetDIBits() failed.")
mss.exception.ScreenShotError: gdi32.GetDIBits() failed.`
```

### Other details

I understand this was an issue that was resolved in #59 however, I still appear to be getting it even after having the latest version of this module. If it helps I can share the full code for this project.

**Comment by NightShadeII** [comment]
Here we go, sorry if it is not well written code, I am more of a hobbyist programmer. I use [https://play2048.co/](url) to get screen input. Hope this is enough to help solve this issue

**Comment by BoboTiG** [comment]
I opened a PR to fix the error. Calling `mss().grab(...)` is not ideal as it will not close opended resources and so, after N calls it will fail.
If performance is critical (I don't think it is there, but correct me if I am wrong), we could find another fix :)

**Comment by BoboTiG** [comment]
Before merging the PR, please test the patch, I did not test it myself.

**Comment by BoboTiG** [comment]
You are welcome :)

**Comment by RamoFX** [comment]
Hello,
I have an error "mss.exception.ScreenShotError: gdi32.GetDIBits() failed.".
I try to do stuff like this:
- Http request from JS
- Python handles it with Flask
- When Python Flask gets a request it will grab a current display view (screenshot), resize it, and convert to base64 and return it as response

It's all ok, but when I send second http request - python mss fails.

(I'll atach both .js and .py files - I don't know how, but it could help)

server.py
`
# Image processing, FPS in console
import mss, cv2, base64, time
import numpy as np
from PIL import Image as i

# Get current frame of second monitor
def getFrame():
    start_time = time.perf_counter()

    # Get frame (only rgb - smaller size)
    frame_rgb     = mss.mss().grab(mss.mss().monitors[2]).rgb # type: bytes, len: 1280*720*3 (w, h, r, g, b)

    # Convert it from bytes to resize
    frame_image   = i.frombytes("RGB", (1280, 720), frame_rgb, "raw", "RGB") # PIL.Image.Image
    frame_array   = np.array(frame_image) # type: numpy.ndarray
    frame_resized = cv2.resize(frame_array, (640, 360), interpolation = cv2.INTER_CUBIC) # type: numpy.ndarray

    # Encode to base64 - prepared to send
    frame_base64  = base64.b64encode(frame_resized) # type: bytes, len: 640*360*4 (w, h, r, g, b, ???)

    print(f'{ round( 1 / (time.perf_counter() - start_time), 2) } fps')
    return frame_base64

# Flask request handler
from flask import Flask, request
from flask_cors import CORS

app = Flask(__name__)
cors = CORS(app)

@app.route('/frame_base64')
def frame_base64():
    return getFrame()

app.run(debug=True, port=7999)

`

script.js (little weir because of compilation from coffeescript)
`
(function() {

  $(document).ready(function() {

    return $.ajax({
      type: 'get',
      url: ' http://127.0.0.1:7999/frame_base64',
      success: (response) => {
        return console.log(response);
      }
    });

  });

}).call(this);

`

Second request raises this:
`
Traceback (most recent call last):
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2463, in __call__

    return self.wsgi_app(environ, start_response)
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2449, in wsgi_app

    response = self.handle_exception(e)
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app

    response = self.full_dispatch_request()
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\web\projects\html-display-stream\backend\server.py", line 33, in frame_base64
    return getFrame()
  File "D:\web\projects\html-display-stream\backend\server.py", line 11, in getFrame
    frame_rgb     = mss.mss().grab(mss.mss().monitors[2]).rgb # type: bytes, len: 1280*720*3 (w, h, r, g, b)
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python37\lib\site-packages\mss\windows.py", line 291, in grab
    raise ScreenShotError("gdi32.GetDIBits() failed.")
mss.exception.ScreenShotError: gdi32.GetDIBits() failed.
`

Additional info:
Windows 7 x64 Service Pack 1
Python 3.7.6
pip 20.0.2
All pip packages have the latest version.

I really hope anyone can help me.
P.S.: Sorry for my bad English.

Thanks

**Comment by BoboTiG** [comment]
@RamoFX could you open a speicifc issue please?
